### ISSUE TITLE
crash on appendChild in node.js 0.11+

### ISSUE THREAD

**Issue by pavelstudeny** [dorny/jsdom-little#1]
When using jsdom-little in node.js newer than 0.10.36, appendChild() fails inside insertBefore() at level1/core.js:553

```
  Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild);
```

with

```
  Cannot set property length of [object Object] which has only a getter
```

This has been already fixed in jsdom:
https://github.com/tmpvar/jsdom/commit/ade9529f45ce4436dbc0447d31e13beab6b72b7d

Patch:

```
@@ -233,7 +233,10 @@ core.NodeList.prototype = {
     this._update();
     return this._length || 0;
   },
-  item: function(index) {
+  set length(length) {
+      return this._length;
+  },
+  item: function (index) {
     this._update();
     return this[index] || null;
   },
```

**Comment by dorny** [comment]
Hi,
thanks for thanks for investigation. This repo wasn't updated since it was created.
I will try to merge upstream changes or at least apply this patch.

**Comment by dorny** [comment]
I've found most recent of jsdom version works well without contextify which means this fork is now almost useless . They just dropped nodejs support in favor of [io.js](https://iojs.org). For now I will just fix this error and update readme.

**Comment by pavelstudeny** [comment]
Yeah, jsdom 4+ doesn't depend on contextify anymore. jsdom 3, running on node.js, still depends on it. A new release with just this error fixed would be great.
